spring.application.name=helo
spring.datasource.url=jdbc:postgresql://localhost:5432/diploma
spring.datasource.username=user
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml
